# -*- coding: utf-8 -*-
"""VLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12q7glekbZWs3O8t54UnxIVAe3pqOiYzH
"""

# !pip install fastapi uvicorn pyngrok nest_asyncio requests pydantic

# !apt-get update -y
# !apt-get install -y zstd
# !curl -fsSL https://ollama.com/install.sh | sh
# !nohup ollama serve > /tmp/ollama.log 2>&1 &
# !sleep 8
# !ollama --version
# !curl -s http://localhost:11434/api/tags

# !ollama pull qwen2.5vl:7b

# lightweight container-friendly VLM service

import os
import re
import json
import asyncio
import requests
import nest_asyncio
from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn

# ======================================
# CONFIG
# ======================================
# Set trong Colab:
# os.environ["NGROK_TOKEN"] = "..."
# os.environ["OLLAMA_URL"] = "http://localhost:11434/api/generate"
# os.environ["OLLAMA_MODEL"] = "qwen2.5vl:7b"

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")
# Fixed Ollama model (do not allow override)
OLLAMA_MODEL = "qwen2.5vl:7b"

nest_asyncio.apply()

app = FastAPI(title="Colab VLM Pair Analyzer", version="1.1.0")


class PairAnalyzeRequest(BaseModel):
    image_base64: str
    meta: dict = {}


def _fallback(issue: str, severity: float = 55.0, confidence: float = 0.2):
    return {
        "joint": "Chưa rõ",
        "issue": issue,
        "severity": float(max(0, min(100, severity))),
        "fix": "Kiểm tra endpoint/model Ollama và thử lại với ảnh rõ hơn",
        "confidence": float(max(0, min(1, confidence))),
    }


@app.get("/")
def root():
    return {
        "status": "running",
        "service": "colab_vlm",
        "model": OLLAMA_MODEL,
        "ollama_url": OLLAMA_URL,
    }


@app.post("/analyze-pair")
def analyze_pair(req: PairAnalyzeRequest):
    prompt = (
        "Bạn là giảng viên thể dục quốc phòng. "
        "Phân tích ảnh ghép: bên trái là MẪU, bên phải là SINH VIÊN. "
        "Nêu lỗi tư thế chính của sinh viên so với mẫu (vai/khuỷu/hông/gối), ngắn gọn.\n\n"
        f"Meta: {json.dumps(req.meta, ensure_ascii=False)}\n\n"
        "Chỉ trả về đúng 1 JSON object, không thêm chữ khác, schema:\n"
        '{"joint":"...", "issue":"...", "severity":0, "fix":"...", "confidence":0.0}'
    )

    try:
        payload = {
            "model": OLLAMA_MODEL,
            "prompt": prompt,
            "images": [req.image_base64],  # base64 raw, không có prefix data:image...
            "stream": False,
            # KHÔNG dùng format=json để tránh 400 với một số model
            "options": {
                "temperature": 0.1,
                "num_predict": 120
            },
        }

        r = requests.post(OLLAMA_URL, json=payload, timeout=300)

        if r.status_code != 200:
            return _fallback(f"Ollama HTTP {r.status_code}: {r.text[:200]}", severity=60, confidence=0.1)

        body = r.json()
        raw = body.get("response", "") or ""

        m = re.search(r"\{[\s\S]*\}", raw)
        if not m:
            return _fallback("Model không trả JSON hợp lệ", severity=55, confidence=0.2)

        data = json.loads(m.group())

        return {
            "joint": str(data.get("joint", "Chưa rõ")),
            "issue": str(data.get("issue", "Chưa rõ lỗi")),
            "severity": float(max(0, min(100, float(data.get("severity", 50))))),
            "fix": str(data.get("fix", "Điều chỉnh theo mẫu")),
            "confidence": float(max(0, min(1, float(data.get("confidence", 0.5))))),
        }

    except Exception as e:
        return _fallback(f"VLM exception: {str(e)}", severity=65, confidence=0.05)


if __name__ == "__main__":
    port = int(os.getenv("VLM_PORT", "8001"))
    config = uvicorn.Config(app=app, host="0.0.0.0", port=port, log_level="info")
    server = uvicorn.Server(config)
    asyncio.get_event_loop().run_until_complete(server.serve())